apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: scanning-readq-job-scaler
spec:
  jobTargetRef:
    template:
      spec:
        containers:
        - name: scanning-readq-job
          image: ams.ocir.io/frsxwtjslf35/scanning-readq-job:0.8
          imagePullPolicy: Always
        restartPolicy: OnFailure
        imagePullSecrets:
        - name: amsocirsecret
    backoffLimit: 0  
  pollingInterval: 5              # Optional. Default: 30 seconds
  maxReplicaCount: 3             # Optional. Default: 100
  successfulJobsHistoryLimit: 0   # Optional. Default: 100. How many completed jobs should be kept.
  failedJobsHistoryLimit: 2       # Optional. Default: 100. How many failed jobs should be kept.
  scalingStrategy:
    strategy: "default"                        # Optional. Default: default. Which Scaling Strategy to use.
    #customScalingQueueLengthDeduction: 0      # Optional. A parameter to optimize custom ScalingStrategy.
    #customScalingRunningJobPercentage: "0.5"  # Optional. A parameter to optimize custom ScalingStrategy.
  triggers:
    - type: metrics-api
      metadata:
        targetValue: "2"
        url: "http://144.21.40.43:3000/stats"
        valueLocation: 'queueStats.queue.visibleMessages'